# Generated by Django 2.2.4 on 2020-11-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
