# Generated by Django 2.2.4 on 2020-11-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='notes',
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
